### ISSUE TITLE
Generate admintech based on device type.

### ISSUE THREAD

**Issue by kagrski** [CiscoDevNet/catalystwan#108]
### Description

F.e. if the device-type is vmanage, then admintech is generated for all the vManages in the cluster.

```yaml
{
   "exclude-cores":true,
   "exclude-logs":true,
   "exclude-tech":false,
   "device-type":"vmanage"
}

**Comment by sbasan** [comment]
Needs special implementation for collecting files generated in this way.
In normal case requests blocks until single file is generated and return file id, so it can be downloaded in next step.
In case device-type is sent, request will return immediataly, as user we need to identify generated files and download them in serial manner.
