### ISSUE TITLE
Pinning logger

### ISSUE THREAD

**Issue by kagrski** [CiscoDevNet/catalystwan#31]
### Description

Pinning logger into another projects. Need to discuss .

**Comment by cicharka** [comment]
Apart from pinning logger to another projects this should consider increasing logging for request:

Currently we have one method that is interface for decoding all requests, `decode_json` -> https://github.com/CiscoDevNet/vManage-client/blob/main/vmngclient/session.py#L187
and therefore it could be nice point for debug logging: it can debug what we are sending, and all of the data returned by that endpoint.

Note that PR https://github.com/CiscoDevNet/vManage-client/pull/33 is removing boilerplate code like `decode_json` so there should be another way to log data from sending/receiving requests.

**Comment by tehAgitto** [comment]
Let's move it to another task - its time to close #33.

**Comment by tehAgitto** [comment]
Debug point for debugging is for now `requests()` method.

```Python
logger.debug(
    f"{method} {full_url}\n \
            args={args if args else None}\n \
            kwargs={kwargs if kwargs else None}"
)
```

**Comment by kagrski** [comment]
Logger is automatically pinned for new endpoint.
