### ISSUE TITLE
Add devices to DeviceModel class

### ISSUE THREAD

**Issue by tmk9090** [CiscoDevNet/catalystwan#375]
### Description

Please add following devices to mentioned class:
vedge-C1111-4PLTEEA
vedge-C1161X-8PLTEP
vedge-C8300-2N2S-4T2X
vedge-C8500L-8S4X
vedge-C8200-1N-4T
vedge-C8200L-1N-4T

**Comment by tehAgitto** [comment]
- [x] vedge-C1111-4PLTEEA #390
- [x] vedge-C1161X-8PLTEP #390
- [x] vedge-C8300-2N2S-4T2X #390
- [ ] vedge-C8500L-8S4X
- [x] vedge-C8200-1N-4T #390
- [x] vedge-C8200L-1N-4T #390
