### ISSUE TITLE
pip modules not finding the new name "catalystwan"

### ISSUE THREAD

**Issue by sashiv20** [CiscoDevNet/catalystwan#455]
### Summary

pip installation succeeds with the older name "vmngclient" but fails with "catalystwan"

### Logs and external information

python3.8 -m pip install catalystwan

ERROR: Could not find a version that satisfies the requirement catalystwan (from versions: none)
ERROR: No matching distribution found for catalystwan

### Reproduction script

python -m pip install catalystwan

### On what platform(s) does it occur?

macOS

### Issue Severity

Medium: There is a workaround

**Comment by tzarski0** [comment]
Facing same issue.

**Comment by sashiv20** [comment]
Issue is resolved now:
 python3.8 -m pip install catalystwan
Collecting catalystwan
  Downloading catalystwan-0.30.0.dev1-py3-none-any.whl.metadata (11 kB)
....
Successfully installed catalystwan-0.30.0.dev1
