### ISSUE TITLE
get_organization() function fails when org-name is not set

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/catalystwan#459]
### Summary

I have a clean vManage with no configuration yet (org-name is also not configured). When I run the below code to check if org-name is already set or no:
```
    vmanage_settings = AdministrationSettingsAPI(vmanage_session)
    org_name = vmanage_settings.get_organization()
```

The function fails with traceback:
```
Traceback (most recent call last):
  File "/Users/tzarski/PycharmProjects/catsdwan-sdk-test/main.py", line 59, in <module>
    main()
  File "/Users/tzarski/PycharmProjects/catsdwan-sdk-test/main.py", line 52, in main
    org_name = vmanage_settings.get_organization()
  File "/Users/tzarski/PycharmProjects/catsdwan-sdk-test/venv/lib/python3.9/site-packages/catalystwan/api/administration.py", line 347, in get_organization
    return create_dataclass(Organization, self.session.get_data(endpoint)[0])
  File "/Users/tzarski/PycharmProjects/catsdwan-sdk-test/venv/lib/python3.9/site-packages/catalystwan/utils/creation_tools.py", line 43, in create_dataclass
    return cls(**filtered_data)
TypeError: __init__() missing 2 required positional arguments: 'name' and 'domain_id'
```

The current code in administration.py does:
```
    def get_organization(self) -> Organization:
        endpoint = "/dataservice/settings/configuration/organization"
        return create_dataclass(Organization, self.session.get_data(endpoint)[0])
```

But when org-name is not set, the self.session.get_data(endpoint)[0] returns empty dict and that's why it fails. I suggest to return none when org-name is not set instead of just failing for example:
```
    def get_organization(self) -> Organization:
        endpoint = "/dataservice/settings/configuration/organization"
        return create_dataclass(Organization, self.session.get_data(endpoint)[0]) if self.session.get_data(endpoint)[0] else None
```

### Reproduction script

from catalystwan.session import create_manager_session
from catalystwan.vmanage_auth import UnauthorizedAccessError
from catalystwan.api.administration import AdministrationSettingsAPI

vmanage_session = create_manager_session(url=vmanage_ip, username=vmanage_user, password=vmanage_password)
vmanage_settings = AdministrationSettingsAPI(vmanage_session)
org_name = vmanage_settings.get_organization()
print(org_name)
vmanage_session.close()

### On what platform(s) does it occur?

Windows, Linux, macOS

### Issue Severity

Medium: There is a workaround

**Comment by kagrski** [comment]
Use 
```python
vmanage_session.endpoints.configuration_settings.get_organizations()
```

instead of 
```
vmanage_session = create_manager_session(url=vmanage_ip, username=vmanage_user, password=vmanage_password)
vmanage_settings = AdministrationSettingsAPI(vmanage_session)
org_name = vmanage_settings.get_organization()
```
It's already deprecated. Sorry for the confusion.

**Comment by tzarski0** [comment]
It works, thanks!
