### ISSUE TITLE
Serial File upload passing wrong data for validity field.

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/catalystwan#465]
### Summary

When you use the code below, the serial file is uploaded to SD-WAN Manager, but the validity field instead of be "valid" or "invalid" string, is class Validity object which leaves the device in unusable state.

<img width="1548" alt="Screenshot 2024-02-13 at 20 33 15" src="https://github.com/CiscoDevNet/catalystwan/assets/92273798/f385380e-3887-4025-9a47-e38bb9059df7">

Workaround is to override the field using below code:
```
serial_file = SerialFilePayload(join(data_dir, f'serial_files/serialFile-v{str(serial_file_version)}.viptela'), Validity.VALID)
serial_file.fields['validity'] = 'valid'
device_inventory.upload_wan_edge_list(serial_file)
```

### Reproduction script

```
from catalystwan.session import create_manager_session
from catalystwan.endpoints.configuration_device_inventory import SerialFilePayload, Validity

manager_session = create_manager_session(url=manager_ip, username=manager_user, password=manager_password)
device_inventory = manager_session.endpoints.configuration_device_inventory
serial_file = SerialFilePayload('serialFile.viptela'), Validity.VALID)
device_inventory.upload_wan_edge_list(serial_file)
```

### On what platform(s) does it occur?

Not Applicable

### Issue Severity

High: Blocking everything

**Comment by sbasan** [comment]
looks like side effect of using (str, Enum) mixin
