### ISSUE TITLE
Add template and templateId fields to DeviceDetailsResponse

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/catalystwan#466]
### Description

DeviceDetailsResponse is missing the template and templateId values. This two keys appear on the JSON response from vManage when device is assigned to a device template. Without this, we are not able to determine if the device (control component or edge) has template assign or not.

**Comment by cicharka** [comment]
@tzarski0 please verify if enhanced DeviceDetailsResponse meet the requirements in your code. On my setup, tested and these fields are available.

**Comment by tzarski0** [comment]
Verified and working. Thank you @cicharka
