### ISSUE TITLE
After PR #471, some parameters return None value incorrectly

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/catalystwan#472]
### Summary

After changes in https://github.com/CiscoDevNet/catalystwan/pull/471/files, lot's of fields are returning None value. See example below. For example before that PR, system_ip in below code was 100.0.0.101 and now is None.

### Logs and external information

DeviceDetailsResponse(
    device_type: vsmart, 
    serial_number: 95963173AACA44458AFB262822946DB9, 
    uuid: 334f71c0-54dc-45c9-9db8-046fbdcde790, 
    management_system_ip: 0.0.0.0, 
    chasis_number: 334f71c0-54dc-45c9-9db8-046fbdcde790, 
    config_operation_mode: vmanage, 
    device_model: vsmart, 
    device_state: READY, 
    validity: valid, 
    platform_family: vsmart, 
    username: --, 
<omitted for brevity>
    state: vBond Updated, 
    global_state: normal, 
    valid: valid, 
    request_token_id: adcd9a66-cd24-4718-9529-de2071a7446f, 
    expiration_date: Feb 14 19:10:31 2026 GMT, 
    expiration_date_long: 1771096231000, 
    device_ip: 100.0.0.101, 
    activity: ['vBond Updated'], 
    state_vedge_list: Sync, 
    cert_install_status: Installed, 
    org: cml-sdwan-lab-tool, 
    personality: vsmart, 
    expiration_status: normal, 
    life_cycle_required: False, 
    hardware_cert_serial_number: NA, 
    subject_serial_number: NA, 
    resource_group: global, 
    id: None, 
    tags: None, 
    draft_mode: Disabled, 
    solution: None, 
    device_lock: None, 
    managed_by: None, 
    configured_site_id: None, 
    <omitted for brevity>
    service_personality: None, 
    upload_source: None, 
    time_remaining_for_expiration: None, 
    domain_id: None, 
    local_system_ip: None, 
    system_ip: None, 
    model_sku: None, 
    site_id: None, 
    host_name: None, 
    sp_organization_name: None, 
    version: 20.6.6, 
    vbond: validator.sdwan.local, 
    vmanage_system_ip: None, 
    vmanage_connection_state: connected, 
    last_updated: None, 
    reachability: reachable, 
    uptime_date: None, 
    default_version: 20.6.6, 
    organization_name: None, 
    available_versions: [], 
    site_name: None, 
)

### Reproduction script

device_inventory = manager_session.endpoints.configuration_device_inventory
control_components = device_inventory.get_device_details('controllers')
print(control_components))

### On what platform(s) does it occur?

Not Applicable

### Issue Severity

High: Blocking everything

**Comment by cicharka** [comment]
Generated aliases are wrong, PR in progress.

**Comment by tzarski0** [comment]
Tested the fix and it's working. Thank you!
